#BSUB -J cascade-rcnn_r101_bifpncarage_8xb8-amp-lsj-200e_DH_GIOU_GA0010
#BSUB -q gpu_v100
#BSUB -n 24
#BSUB -o %J.out
#BSUB -e %J.err
#BSUB -gpu "num=8:mode=exclusive_process:aff=yes"
module load anaconda3
module load cuda-11.6
module load gcc-9.3.0
source activate mmdet3
cd ~/mmdet3
bash tools/dist_train.sh myconfig/VisDrone-seu/cascade_rcnn/cascade-rcnn_r101_bifpncarage_8xb8-amp-lsj-200e_DH_GIOU_GA0010.py 8